# Tensorflow Dataset

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.15.5'

In [3]:
def next_sample(data_iter):
    session = tf.get_default_session()
    if not session:
        return None
    session.run(data_iter.initializer)
    a = session.run(data_iter.get_next())
    return a

In [4]:
data = tf.data.Dataset.from_tensors(np.random.random(size = [3, 4]))
data

<DatasetV1Adapter shapes: (3, 4), types: tf.float64>

In [5]:
data = data.repeat(4) # repeat 4 times, if data = data.repeat() means repeat forever.

In [6]:
with tf.Session() as sess:
    data_iter = data.make_initializable_iterator()
    sample = next_sample(data_iter)
    print(sample)

Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_initializable_iterator(dataset)`.
[[0.91233607 0.43481143 0.59767966 0.37813157]
 [0.30968791 0.54455042 0.51754028 0.78820589]
 [0.43060362 0.23526971 0.52546393 0.09690097]]


In [7]:
data = data.batch(4)

In [8]:
with tf.Session() as sess:
    data_iter = data.make_initializable_iterator()
    sample = next_sample(data_iter)
    print(sample)

[[[0.91233607 0.43481143 0.59767966 0.37813157]
  [0.30968791 0.54455042 0.51754028 0.78820589]
  [0.43060362 0.23526971 0.52546393 0.09690097]]

 [[0.91233607 0.43481143 0.59767966 0.37813157]
  [0.30968791 0.54455042 0.51754028 0.78820589]
  [0.43060362 0.23526971 0.52546393 0.09690097]]

 [[0.91233607 0.43481143 0.59767966 0.37813157]
  [0.30968791 0.54455042 0.51754028 0.78820589]
  [0.43060362 0.23526971 0.52546393 0.09690097]]

 [[0.91233607 0.43481143 0.59767966 0.37813157]
  [0.30968791 0.54455042 0.51754028 0.78820589]
  [0.43060362 0.23526971 0.52546393 0.09690097]]]


In [9]:
data = tf.data.Dataset.from_tensor_slices(np.random.random(size = [3, 4]))
data

<DatasetV1Adapter shapes: (4,), types: tf.float64>

In [10]:
data = data.batch(3)
data = data.repeat(10)

In [11]:
with tf.Session() as sess:
    data_iter = data.make_initializable_iterator()
    sample = next_sample(data_iter)
    print(sample)

[[0.13874757 0.69917287 0.60047035 0.13787645]
 [0.7643512  0.69037768 0.24441    0.40883677]
 [0.72602262 0.57315107 0.77520502 0.13347721]]
